[2025-04-17T05:17:05.334+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: model_downloader_dag.download_embedding_model manual__2025-04-17T05:15:02.311865+00:00 [queued]>
[2025-04-17T05:17:05.339+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: model_downloader_dag.download_embedding_model manual__2025-04-17T05:15:02.311865+00:00 [queued]>
[2025-04-17T05:17:05.339+0000] {taskinstance.py:1331} INFO - Starting attempt 2 of 3
[2025-04-17T05:17:05.346+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): download_embedding_model> on 2025-04-17 05:15:02.311865+00:00
[2025-04-17T05:17:05.349+0000] {standard_task_runner.py:57} INFO - Started process 272 to run task
[2025-04-17T05:17:05.352+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'model_downloader_dag', 'download_embedding_model', 'manual__2025-04-17T05:15:02.311865+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/Download_model.py', '--cfg-path', '/tmp/tmp7cyjdkab']
[2025-04-17T05:17:05.352+0000] {standard_task_runner.py:85} INFO - Job 10: Subtask download_embedding_model
[2025-04-17T05:17:05.388+0000] {task_command.py:410} INFO - Running <TaskInstance: model_downloader_dag.download_embedding_model manual__2025-04-17T05:15:02.311865+00:00 [running]> on host 5e6e96c1853a
[2025-04-17T05:17:05.431+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='model_downloader_dag' AIRFLOW_CTX_TASK_ID='download_embedding_model' AIRFLOW_CTX_EXECUTION_DATE='2025-04-17T05:15:02.311865+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-17T05:15:02.311865+00:00'
[2025-04-17T05:17:05.431+0000] {Download_model.py:134} INFO - Checking availability of embedding model: nomic-embed-text
[2025-04-17T05:17:05.436+0000] {Download_model.py:146} WARNING - Embedding model is not available: 404
[2025-04-17T05:17:05.437+0000] {Download_model.py:149} INFO - Downloading embedding model nomic-embed-text
[2025-04-17T05:17:05.442+0000] {Download_model.py:169} ERROR - Error checking/downloading embedding model: [Errno 13] Permission denied: 'ollama'
[2025-04-17T05:17:05.442+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Download_model.py", line 150, in download_embedding_model
    subprocess.run(
  File "/usr/local/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'ollama'
[2025-04-17T05:17:05.448+0000] {taskinstance.py:1368} INFO - Marking task as UP_FOR_RETRY. dag_id=model_downloader_dag, task_id=download_embedding_model, execution_date=20250417T051502, start_date=20250417T051705, end_date=20250417T051705
[2025-04-17T05:17:05.456+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 10 for task download_embedding_model ([Errno 13] Permission denied: 'ollama'; 272)
[2025-04-17T05:17:05.484+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2025-04-17T05:17:05.492+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
